'use client';

import { useMemo } from 'react';
import { encodeBarcode, layoutBarcode, type BarcodeSvgOptions } from '@/lib/barcode';

export interface BarcodeProps extends BarcodeSvgOptions {
  value: string;
  /** CSS width of the rendered SVG; the viewBox scales to fit. */
  width?: number | string;
  /** Fallback content when the value cannot be encoded. */
  fallback?: React.ReactNode;
  className?: string;
}

/** Inline SVG barcode (EAN-13 or Code 128) generated by `lib/barcode.ts`. */
export default function Barcode({ value, width = '100%', fallback, className, ...opts }: BarcodeProps) {
  const layout = useMemo(() => {
    try {
      return layoutBarcode(encodeBarcode(value), opts);
    } catch {
      return null;
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [value, opts.moduleWidth, opts.height, opts.showText, opts.fontSize, opts.quietZone]);

  if (!layout) return <>{fallback ?? <span style={{ fontFamily: 'monospace' }}>{value}</span>}</>;

  return (
    <svg
      className={className}
      viewBox={`0 0 ${layout.width} ${layout.height}`}
      width={width}
      preserveAspectRatio="xMidYMid meet"
      shapeRendering="crispEdges"
      role="img"
      aria-label={layout.text}
    >
      <rect x={0} y={0} width={layout.width} height={layout.height} fill="#fff" />
      {layout.rects.map((r, i) => (
        <rect key={i} x={r.x} y={0} width={r.width} height={layout.barHeight} fill="#000" />
      ))}
      {(opts.showText ?? true) && (
        <text
          x={layout.width / 2}
          y={layout.textY}
          textAnchor="middle"
          fontFamily="monospace"
          fontSize={opts.fontSize ?? 10}
          fill="#000"
        >
          {layout.text}
        </text>
      )}
    </svg>
  );
}
