import { chromium } from 'playwright';
import { readFileSync } from 'node:fs';
const BASE='https://t-pos.tdev2022.com';
const th=JSON.parse(readFileSync('i18n/messages/th.json','utf8'));
const L=(p)=>p.split('.').reduce((o,k)=>o?.[k],th);
const SP='C:/Users/User/AppData/Local/Temp/claude/D--workspace-pos/ee802bf6-41d6-47f5-a9a0-4c42c0ef4760/scratchpad';
const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:1280,height:900},locale:'th-TH'});
const p=await ctx.newPage();
p.on('pageerror',(e)=>console.log('PAGEERROR:', String(e).slice(0,400)));
p.on('console',(m)=>{ if(['error','warning'].includes(m.type())) console.log(m.type().toUpperCase()+':', m.text().slice(0,250)); });
await p.goto(`${BASE}/login`,{waitUntil:'domcontentloaded'});
await p.getByLabel(L('auth.storeCode')).fill('BBR');
await p.getByLabel(L('auth.username')).fill('owner');
await p.getByLabel(L('auth.password')).first().fill('Owner12345');
await p.getByRole('button',{name:L('auth.signIn'),exact:true}).click();
await p.waitForURL(/\/(dashboard|pos)/,{timeout:45000});
await p.goto(`${BASE}/settings/units`,{waitUntil:'domcontentloaded'});
await p.waitForTimeout(5000);
await p.screenshot({path:`${SP}/live-units.png`});
console.log('main html len:', await p.evaluate(()=>document.querySelector('main')?.innerHTML.length ?? -1));
console.log('main text:', await p.evaluate(()=>(document.querySelector('main')?.innerText ?? '').slice(0,200)));
console.log('session role:', await p.evaluate(()=>JSON.parse(localStorage.getItem('pos.session')||'{}')?.user?.role));
await b.close();
